### ISSUE TITLE
Conv changelog

### ISSUE THREAD

**Issue by peduarte** [ellerbrock/cz-conventional-changelog-emoji#4]

**Comment by ellerbrock** [comment]
hey @peduarte 

what do you mean by that?
do you mean a description how to install?
in that case you can find the setup introduction here: https://github.com/ellerbrock/cz-conventional-changelog-emoji#hell-yeah-how

cheers maik

**Comment by peduarte** [comment]
Hey man, sorry about this, I was testing out Commitizen and I thought I created this issue in my test repo! My bad! 🙈
